/**
 * Static pages the agent builds, served by the bridge.
 *
 * The agent has no network and needs none for this: it writes HTML, CSS and JS
 * into `handoff-out/pages/<slug>/` and the trusted side serves them. Same
 * pattern as every other capability here — the agent produces, the bridge
 * performs — and it costs `tulip-lan` no reachable host.
 *
 * **On its own hostname, and that is not a preference.** Served from the panel's
 * origin, agent-authored JavaScript would be same-origin with the operator's
 * session: one `fetch('/api/settings')` from a page you opened would carry your
 * panel cookie and let the agent edit its own audience, read every message and
 * hold delivery. A strict CSP can *mostly* contain that, and "mostly" is the
 * wrong word for the only thing standing between a built page and the
 * deployment.
 *
 * Nor can it be sandboxed into an opaque origin, which would be genuinely safe:
 * `localStorage` throws there, and saving state in the browser is most of what
 * these pages are for. Storage needs a real origin, so it gets a real hostname.
 *
 * What the pages themselves may do is bounded by their own CSP: same-origin
 * assets, inline script and style so a single file works, and `connect-src
 * 'none'` — so a page can keep state in the browser and cannot send it
 * anywhere. A page that could phone home would be a way for the agent to reach
 * the internet through a visitor's browser, which is the containment property
 * wearing a disguise.
 */
import { createReadStream, existsSync, mkdirSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { basename, extname, join, resolve, sep } from 'node:path';
import type { ServerResponse } from 'node:http';
import { outPaths } from '@tulip/shared';
import { log } from './log.js';

/** Slugs are generated by the agent and land in a URL, so they are narrow. */
export const SLUG = /^[a-z0-9][a-z0-9-]{2,47}$/;

/** Nothing outside this is served, whatever is written into the directory. */
const TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
};

/** A Pi with one disk, and pages nobody is watching the size of. */
const MAX_PAGES = 40;
const MAX_FILES_PER_PAGE = 40;
const MAX_PAGE_BYTES = 8 * 1024 * 1024;

export interface PageSummary {
  readonly slug: string;
  readonly files: number;
  readonly bytes: number;
  readonly at: number;
}

/** Where pages are reachable, or null when no hostname has been configured. */
export function pagesHost(): string | null {
  const host = (process.env['TULIP_PAGES_HOST'] ?? '').trim().toLowerCase();
  return host.length > 0 ? host : null;
}

/** Whether this request is for a page rather than for the panel. */
export function isPagesRequest(hostHeader: string | undefined): boolean {
  const configured = pagesHost();
  if (configured === null || typeof hostHeader !== 'string') return false;
  return hostHeader.toLowerCase().split(':')[0] === configured;
}

function measure(slug: string): { files: number; bytes: number; at: number } | null {
  const dir = outPaths.page(slug);
  let files = 0;
  let bytes = 0;
  let at = 0;
  try {
    for (const name of readdirSync(dir)) {
      const stat = statSync(join(dir, name));
      if (!stat.isFile()) continue;
      files += 1;
      bytes += stat.size;
      at = Math.max(at, stat.mtimeMs);
    }
  } catch {
    return null;
  }
  return files === 0 ? null : { files, bytes, at };
}

export function listPages(): PageSummary[] {
  let slugs: string[] = [];
  try {
    slugs = readdirSync(outPaths.pages, { withFileTypes: true })
      .filter((d) => d.isDirectory() && SLUG.test(d.name))
      .map((d) => d.name);
  } catch {
    return [];
  }
  return slugs
    .flatMap((slug) => {
      const stat = measure(slug);
      return stat === null ? [] : [{ slug, ...stat }];
    })
    .sort((a, b) => b.at - a.at);
}

export type Published = { ok: true; url: string } | { ok: false; error: string };

/** Pictures one page may hold. Enough to carry an argument, not a gallery. */
export const MAX_IMAGES_PER_PAGE = 5;

/** How many generated pictures a page already has. */
export function imageCount(slug: string): number {
  try {
    return readdirSync(outPaths.page(slug)).filter((n) => n.toLowerCase().endsWith('.jpg')).length;
  } catch {
    return 0;
  }
}

/**
 * Write a generated picture into a page.
 *
 * Refuses rather than overwrites when the page is full, and refuses a name that
 * is not a slug — this lands as a filename the agent then references from its
 * own HTML, so it is exactly the input a path check exists for.
 */
export function writePageImage(slug: string, name: string, data: Buffer): Published {
  if (!SLUG.test(slug) || !SLUG.test(name)) return { ok: false, error: 'that name is not usable as a file' };
  const dir = outPaths.page(slug);
  const root = resolve(outPaths.pages);
  const target = resolve(dir, `${name}.jpg`);
  if (!target.startsWith(root + sep)) return { ok: false, error: 'that name is not usable as a file' };
  try {
    mkdirSync(dir, { recursive: true });
    writeFileSync(target, data, { mode: 0o644 });
    log('pages.image', { slug, name, bytes: data.length });
    return { ok: true, url: `${name}.jpg` };
  } catch (err) {
    return { ok: false, error: `could not write the picture (${(err as Error).name})` };
  }
}

/**
 * Check what the agent has written and hand back the address.
 *
 * Publishing *is* writing the files; this is the moment the bridge looks at
 * them. Refusals are worded for the agent, because it is the only reader and it
 * can act on them — "there is no index.html" is a thing it can fix.
 */
export function publishPage(slug: string): Published {
  const host = pagesHost();
  if (host === null) return { ok: false, error: 'no page hostname is configured on this deployment' };
  if (!SLUG.test(slug)) {
    return { ok: false, error: 'a page name is 3-48 characters of lowercase letters, digits and dashes' };
  }

  const dir = outPaths.page(slug);
  if (!existsSync(join(dir, 'index.html'))) {
    return { ok: false, error: `write ${slug}/index.html first — a page is served from its index` };
  }
  const stat = measure(slug);
  if (stat === null) return { ok: false, error: 'that page has no files in it' };
  if (stat.files > MAX_FILES_PER_PAGE) {
    return { ok: false, error: `a page may have at most ${String(MAX_FILES_PER_PAGE)} files` };
  }
  if (stat.bytes > MAX_PAGE_BYTES) return { ok: false, error: 'that page is larger than 8 MB' };

  const existing = listPages();
  if (existing.length > MAX_PAGES && !existing.some((p) => p.slug === slug)) {
    return { ok: false, error: `there are already ${String(MAX_PAGES)} pages — delete one first` };
  }

  log('pages.published', { slug, files: stat.files, bytes: stat.bytes });
  return { ok: true, url: `https://${host}/${slug}/` };
}

export function deletePage(slug: string): boolean {
  if (!SLUG.test(slug)) return false;
  const root = resolve(outPaths.pages);
  const target = resolve(root, slug);
  if (!target.startsWith(root + sep)) return false;
  try {
    rmSync(target, { recursive: true, force: true });
    log('pages.deleted', { slug });
    return true;
  } catch (err) {
    log('pages.deleteFailed', { slug, err: String((err as Error).message) });
    return false;
  }
}

/**
 * Serve one file from one page.
 *
 * The agent has write access to this directory, so the path is resolved and
 * then re-checked against the root — the same belt-and-braces the outbox file
 * resolver uses, and for the same reason: a name that passed a check is not the
 * same object as a name opened a moment later.
 */
/** Where the pages host sends anyone who arrives at its root. */
const ROOT_REDIRECT = 'https://hfs2s.app/';

/**
 * The design kit, served from a reserved prefix.
 *
 * A page gets Tulip's palette, type and motion by linking two files rather than
 * by the agent reinventing them each time — which is both cheaper and the only
 * way a set of pages looks like one product. Reserved rather than a slug: no
 * page can be called `_kit`, so nothing the agent writes can shadow it.
 */
const KIT_PREFIX = '_kit';
// Beside the compiled bridge, not in `bridge/assets` — the image ships built
// output only, and a path into the source tree resolves to nothing at runtime.
const KIT_DIR = new URL('./web/pagekit/', import.meta.url).pathname;

export function servePage(res: ServerResponse, url: URL): void {
  const parts = url.pathname.split('/').filter((p) => p.length > 0);

  const common = {
    // Same rules as any built page: no outbound connections, nothing embedded.
    'content-security-policy':
      "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; " +
      "img-src 'self' data: blob:; font-src 'self' data:; media-src 'self' data:; " +
      "connect-src 'none'; form-action 'none'; base-uri 'none'; frame-ancestors 'none'",
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'no-referrer',
    'x-robots-tag': 'noindex, nofollow',
    'cache-control': 'no-cache',
  };

  if (parts[0] === KIT_PREFIX) {
    const file = parts[1] ?? '';
    const type = file === 'kit.css' ? 'text/css; charset=utf-8'
      : file === 'kit.js' ? 'text/javascript; charset=utf-8'
        : null;
    if (type === null) {
      res.writeHead(404, { ...common, 'content-type': 'text/plain' }).end('no such file\n');
      return;
    }
    const path = resolve(KIT_DIR, file);
    if (!existsSync(path)) {
      res.writeHead(404, { ...common, 'content-type': 'text/plain' }).end('the kit was not built into this image\n');
      return;
    }
    res.writeHead(200, {
      ...common,
      'content-type': type,
      'content-length': statSync(path).size,
      // Immutable in practice — it changes only when the image is rebuilt, and
      // a page that caches it loads instantly on a second visit.
      'cache-control': 'public, max-age=3600',
    });
    createReadStream(path).pipe(res);
    return;
  }

  // The root is not a directory. Listing every page would make each of them
  // discoverable by anyone who finds the hostname, when the point of a page is
  // that its author hands somebody the link. The operator's own listing lives
  // in the panel, behind the token, where it belongs.
  if (parts.length === 0) {
    res.writeHead(302, { ...common, location: ROOT_REDIRECT }).end();
    return;
  }

  const slug = parts[0] ?? '';
  if (!SLUG.test(slug)) {
    res.writeHead(404, { 'content-type': 'text/plain' }).end('no such page\n');
    return;
  }

  const rest = parts.slice(1);
  const name = rest.length === 0 ? 'index.html' : rest[rest.length - 1] ?? 'index.html';
  if (name !== basename(name) || name.startsWith('.')) {
    res.writeHead(400, { 'content-type': 'text/plain' }).end('bad request\n');
    return;
  }
  const type = TYPES[extname(name).toLowerCase()];
  if (type === undefined) {
    res.writeHead(404, { 'content-type': 'text/plain' }).end('not a servable file\n');
    return;
  }

  const root = resolve(outPaths.pages);
  const candidate = resolve(root, slug, name);
  if (!candidate.startsWith(root + sep) || !existsSync(candidate)) {
    res.writeHead(404, { 'content-type': 'text/plain' }).end('no such page\n');
    return;
  }

  res.writeHead(200, {
    'content-type': type,
    'content-length': statSync(candidate).size,
    // Same-origin assets, inline script and style so one file is enough, and no
    // outbound connections at all: a page may keep state in the browser and may
    // not send it anywhere. A page that could reach the network would be the
    // agent reaching it through a visitor.
    'content-security-policy':
      "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; " +
      "img-src 'self' data: blob:; font-src 'self' data:; media-src 'self' data:; " +
      "connect-src 'none'; form-action 'none'; base-uri 'none'; frame-ancestors 'none'",
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'no-referrer',
    'x-robots-tag': 'noindex, nofollow',
    'cache-control': 'no-cache',
  });
  createReadStream(candidate).pipe(res);
}
