/**
 * Static pages the agent builds, served by the bridge.
 *
 * The agent has no network and needs none for this: it writes HTML, CSS and JS
 * into `handoff-out/pages/<slug>/` and the trusted side serves them. Same
 * pattern as every other capability here — the agent produces, the bridge
 * performs — and it costs `tulip-lan` no reachable host.
 *
 * **On its own hostname, and that is not a preference.** Served from the panel's
 * origin, agent-authored JavaScript would be same-origin with the operator's
 * session: one `fetch('/api/settings')` from a page you opened would carry your
 * panel cookie and let the agent edit its own audience, read every message and
 * hold delivery. A strict CSP can *mostly* contain that, and "mostly" is the
 * wrong word for the only thing standing between a built page and the
 * deployment.
 *
 * Nor can it be sandboxed into an opaque origin, which would be genuinely safe:
 * `localStorage` throws there, and saving state in the browser is most of what
 * these pages are for. Storage needs a real origin, so it gets a real hostname.
 *
 * What the pages themselves may do is bounded by their own CSP: same-origin
 * assets, inline script and style so a single file works, and same-origin
 * connections only. This lets an interactive page update its own database
 * without opening a route to any other origin.
 */
import {
  closeSync, constants as fsConstants, createReadStream, existsSync, fstatSync, fsyncSync, lstatSync, mkdirSync,
  openSync, readSync, readdirSync, readlinkSync, realpathSync, renameSync, rmSync, statSync, writeFileSync,
} from 'node:fs';
import { DatabaseSync } from 'node:sqlite';
import { basename, dirname, extname, join, resolve, sep } from 'node:path';
import { Transform, pipeline } from 'node:stream';
import type { IncomingMessage, ServerResponse } from 'node:http';
import { randomBytes, scryptSync, timingSafeEqual } from 'node:crypto';
import { outPaths } from '@2lp/shared';
import type { Config } from './config.js';
import { identities, matchesList } from './jid.js';
import { log } from './log.js';

/** Slugs are generated by the agent and land in a URL, so they are narrow. */
export const SLUG = /^[a-z0-9][a-z0-9-]{2,47}$/;

/** Nothing outside this is served, whatever is written into the directory. */
const TYPES: Record<string, string> = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.json': 'application/json',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.jpg': 'image/jpeg',
  '.jpeg': 'image/jpeg',
  '.webp': 'image/webp',
  '.gif': 'image/gif',
  '.ico': 'image/x-icon',
  '.woff2': 'font/woff2',
  '.txt': 'text/plain; charset=utf-8',
  // Documents and media a page carries whole: the PDF a digest was written
  // from, the podcast episode it is about. Served with byte ranges (below) so
  // a browser can seek in an hour of audio and a PDF viewer can page.
  '.pdf': 'application/pdf',
  '.m4a': 'audio/mp4',
  '.mp3': 'audio/mpeg',
  '.ogg': 'audio/ogg',
  '.wav': 'audio/wav',
  '.mp4': 'video/mp4',
  '.webm': 'video/webm',
  // A database, for a page that offers it as a download. Pages themselves read
  // it as `<name>.js` — see `serveDatabase`.
  '.sqlite': 'application/vnd.sqlite3',
  '.sqlite3': 'application/vnd.sqlite3',
  '.db': 'application/vnd.sqlite3',
};

/** What a page's database may be called — the same three the kit accepts. */
const DATABASES = new Set(['.sqlite', '.sqlite3', '.db']);
const SQLITE_HEADER = Buffer.from('SQLite format 3\0', 'latin1');

/** A Pi with one disk, and pages nobody is watching the size of. */
const MAX_PAGES = 40;
const MAX_FILES_PER_PAGE = 40;
// 256 MB rather than the original 8 MB: a page that carries a podcast episode
// (40-50 MB each as an m4a) or the PDF it was written from needs the room, and
// at 40 pages the worst case is 10 GB on a 58 GB disk with 27 GB free. Files are
// streamed to the browser, so the cap is disk, not memory — except index.html
// and a database, which are read whole up to this size by readPageFile.
const MAX_PAGE_BYTES = 256 * 1024 * 1024;
const MAX_PAGE_LABEL = `${String(MAX_PAGE_BYTES / (1024 * 1024))} MB`;

export interface PageSummary {
  readonly slug: string;
  readonly files: number;
  readonly bytes: number;
  readonly at: number;
}

/** Where pages are reachable, or null when no hostname has been configured. */
export function pagesHost(): string | null {
  const host = (process.env['TULIP_PAGES_HOST'] ?? '').trim().toLowerCase();
  return host.length > 0 ? host : null;
}

/** Whether this request is for a page rather than for the panel. */
export function isPagesRequest(hostHeader: string | undefined): boolean {
  const configured = pagesHost();
  if (configured === null || typeof hostHeader !== 'string') return false;
  return hostHeader.toLowerCase().split(':')[0] === configured;
}

function measure(slug: string): { files: number; bytes: number; at: number } | null {
  const dir = outPaths.page(slug);
  let files = 0;
  let bytes = 0;
  let at = 0;
  try {
    for (const name of readdirSync(dir)) {
      const stat = lstatSync(join(dir, name));
      if (!stat.isFile()) continue;
      files += 1;
      bytes += stat.size;
      at = Math.max(at, stat.mtimeMs);
    }
  } catch {
    return null;
  }
  return files === 0 ? null : { files, bytes, at };
}

export function listPages(): PageSummary[] {
  let slugs: string[] = [];
  try {
    slugs = readdirSync(outPaths.pages, { withFileTypes: true })
      .filter((d) => d.isDirectory() && SLUG.test(d.name))
      .map((d) => d.name);
  } catch {
    return [];
  }
  return slugs
    .flatMap((slug) => {
      const stat = measure(slug);
      return stat === null ? [] : [{ slug, ...stat }];
    })
    .sort((a, b) => b.at - a.at);
}


/**
 * Look a slug up in a config map without asking the prototype.
 *
 * A slug is attacker-adjacent — the agent chooses it, on behalf of whoever it
 * is talking to — and `SLUG` happily matches `constructor`, `tostring` is not a
 * problem but `constructor` is: a plain object answers `map['constructor']`
 * with a function from `Object.prototype` rather than `undefined`.
 *
 * That is not theoretical in either place it is used. In `mayChange` the value
 * is then called as `granted.includes(...)`, which throws a TypeError out of
 * the outbox handler; in `pageAuthorised` a page named that way is treated as
 * password-protected and no password can ever open it. One fails loudly and
 * wrongly, the other fails quietly and permanently.
 */
function own<T>(map: Readonly<Record<string, T>>, key: string): T | undefined {
  return Object.hasOwn(map, key) ? map[key] : undefined;
}

/**
 * May this chat change this page?
 *
 * The whole of the authorisation decision, in one place, so the three verbs that
 * write a page cannot drift apart from each other. Read `pages.grants` in
 * config.ts for why the unit is a chat rather than a person.
 *
 * Note what this does *not* do: it cannot stop the agent writing
 * `pages/<slug>/index.html` with a shell, because `/handoff/out` is mounted
 * read-write into its container and `servePage` reads from disk — so writing the
 * file is publishing, and a check on the verb is a check on the polite path
 * only. Moving the served tree onto a volume the agent cannot reach is what
 * turns this from a rule into an enforcement, and until that lands this is worth
 * exactly what the agent's cooperation is worth.
 */
export function mayChange(
  config: Config,
  slug: string,
  chatKey: string,
  chat: { readonly jid: string; readonly altJid: string | null; readonly isGroup: boolean } | null,
): boolean {
  const granted = own(config.pages.grants, slug);
  // An absent grant and an empty one are different answers: nobody has claimed
  // this page, versus somebody claimed it for no one.
  if (granted === undefined) return config.pages.open;
  if (granted.includes(chatKey)) return true;

  // Granted by phone number or linked id — the only way to hand a page to
  // somebody who has never written, because a chat key does not exist until
  // they do. Direct chats only: a group's jid is the group's, not a member's,
  // so a number could otherwise authorise a room rather than a person.
  if (chat === null || chat.isGroup) return false;
  return matchesList({ jids: granted }, identities(chat.jid, chat.altJid));
}

/** Why a refusal, worded for the agent, which is the only reader. */
export const NOT_YOURS =
  'that page is not yours to change — the operator has granted it to another conversation';

/** Why a refusal when nothing may be created at all. */
export const NO_NEW_PAGES =
  'new pages are switched off by the operator — ask them to grant you one';

export type Published = { ok: true; url: string } | { ok: false; error: string };

/**
 * A starting page, already wearing the house style.
 *
 * The brief told the agent to link the kit and it wrote its own stylesheet
 * anyway — an instruction competing with a very strong prior about what a
 * self-contained HTML file looks like, and losing. A scaffold does not argue
 * with the prior: the first thing in the file is already the right thing, and
 * editing beats starting over.
 *
 * Refuses to overwrite. A page being rebuilt from scratch is the agent's call,
 * not a side effect of asking for a starting point.
 */
export function scaffoldPage(slug: string, title: string): Published {
  const host = pagesHost();
  if (host === null) return { ok: false, error: 'no page hostname is configured on this deployment' };
  if (!SLUG.test(slug)) {
    return { ok: false, error: 'a page name is 3-48 characters of lowercase letters, digits and dashes' };
  }
  const dir = outPaths.page(slug);
  const index = join(dir, 'index.html');
  if (existsSync(index)) return { ok: false, error: `${slug}/index.html already exists — edit it` };

  const safe = title.replace(/[&<>"']/g, ' ').trim().slice(0, 120) || 'A page';
  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${safe}</title>
<link rel="stylesheet" href="/_kit/kit.css">
<script src="/_kit/kit.js" defer></script>
</head>
<body>
<main class="wrap">

  <section class="reveal">
    <h1>${safe}</h1>
    <p class="lede">One sentence saying what this is and who it is for.</p>
  </section>

  <section class="reveal">
    <h2>A section</h2>
    <p>Ordinary paragraphs. Put <code>class="reveal"</code> on a section and it
      settles into place as the reader reaches it.</p>
  </section>

  <section class="reveal">
    <div class="grid">
      <div class="card"><h3>A card</h3><p>Cards, buttons and tags are in the kit.</p></div>
      <div class="card"><h3>Another</h3><p>Delete what you do not need.</p></div>
    </div>
  </section>

</main>
</body>
</html>
`;
  try {
    mkdirSync(dir, { recursive: true });
    writeFileSync(index, html, { mode: 0o644 });
    log('pages.scaffolded', { slug });
    // The reminder rides on the answer the agent is already reading, because a
    // rule in the brief did not survive contact with a long task: building a
    // page is minutes of silence at the other end, and silence reads as being
    // ignored.
    return { ok: true, url: `${slug}/index.html` };
  } catch (err) {
    return { ok: false, error: `could not write the page (${(err as Error).name})` };
  }
}

/**
 * Open one file of one page for reading, without following a link anywhere.
 *
 * The agent writes this directory and the bridge reads it — in the bridge's own
 * mount namespace, where `/state` holds the WhatsApp credentials. A symlink
 * planted here (`ln -s /state/session/creds.json pages/x/creds.json`) is
 * resolved by *this* process, so a check on the name says nothing about where
 * it leads: `resolve` works on strings. That string check used to be the whole
 * of it, and a planted link was served to anyone holding the address.
 *
 * So, the treatment `resolveOutboundFile` in outbox.ts gives the outbox, for
 * the same reason. One open. `O_NOFOLLOW`, so the kernel refuses a linked leaf.
 * `/proc/self/fd` to say what was actually opened, which catches a linked page
 * directory — or `pages` itself swapped for a link — that `O_NOFOLLOW` on the
 * leaf cannot see. `O_NONBLOCK`, so a planted FIFO cannot hang the event loop
 * that also serves the panel. `fstat`, so only a regular file is read. The
 * caller then reads the descriptor, never the name again.
 *
 * Null for every refusal, which the caller answers as 404: as far as a visitor
 * can tell, there is no such file.
 */
function openPageFile(slug: string, name: string): { fd: number; size: number } | null {
  if (!SLUG.test(slug) || name !== basename(name) || name.startsWith('.')) return null;
  const root = resolve(outPaths.pages);
  let expected: string;
  try {
    const stat = lstatSync(root);
    if (stat.isSymbolicLink() || !stat.isDirectory()) return null;
    // The parent is the volume's mount point, which the agent cannot replace.
    // `pages` inside it is the agent's to swap, so it is spelled out, not resolved.
    expected = join(realpathSync(dirname(root)), basename(root), slug, name);
  } catch {
    return null;
  }

  const path = join(root, slug, name);
  let fd: number;
  try {
    fd = openSync(path, fsConstants.O_RDONLY | fsConstants.O_NOFOLLOW | fsConstants.O_NONBLOCK);
  } catch {
    return null;
  }
  try {
    // /proc is authoritative on Linux, which is production. Elsewhere — a
    // developer's Mac — realpath is the best available.
    const opened = describeFd(fd) ?? realpathSync(path);
    const stat = fstatSync(fd);
    if (opened === expected && stat.isFile()) return { fd, size: stat.size };
  } catch {
    // Refused below, like everything else that is not plainly a file.
  }
  closeSync(fd);
  return null;
}

/** The real path behind a descriptor, on Linux. Null where there is no /proc. */
function describeFd(fd: number): string | null {
  try {
    return readlinkSync(`/proc/self/fd/${String(fd)}`);
  } catch {
    return null;
  }
}

/** Up to `limit` bytes of one page's file, read the same careful way. */
function readPageFile(slug: string, name: string, limit: number): Buffer | null {
  const file = openPageFile(slug, name);
  if (file === null) return null;
  try {
    const data = Buffer.alloc(Math.min(file.size, limit));
    let read = 0;
    while (read < data.length) {
      const n = readSync(file.fd, data, read, data.length - read, read);
      if (n <= 0) break;
      read += n;
    }
    return data.subarray(0, read);
  } catch {
    return null;
  } finally {
    closeSync(file.fd);
  }
}

/** Whether a page opted out of the house style, so publishing can say so. */
export function usesKit(slug: string): boolean {
  const html = readPageFile(slug, 'index.html', MAX_PAGE_BYTES);
  // Unreadable is not the same as unstyled; do not nag about it.
  return html === null || html.toString('utf8').includes('/_kit/kit.css');
}

/**
 * What is wrong with a page's databases, worded for the agent.
 *
 * Said at publish time and never a refusal: each of these is a way a page ends
 * up querying something other than the database the agent just wrote, and each
 * is something the agent can fix — so it is said where the agent is looking,
 * rather than discovered by a visitor as an empty table.
 */
export function databaseNotes(slug: string): string[] {
  let names: string[];
  try {
    names = readdirSync(outPaths.page(slug));
  } catch {
    return [];
  }
  const databases = names.filter((n) => !n.startsWith('.') && DATABASES.has(extname(n).toLowerCase()));
  const notes: string[] = [];
  for (const name of databases) {
    const head = readPageFile(slug, name, SQLITE_HEADER.length);
    if (head === null) {
      notes.push(`${name} cannot be served — it must be an ordinary file, not a link`);
      continue;
    }
    // Empty is allowed: the kit opens it as an empty database.
    if (head.length > 0 && !head.equals(SQLITE_HEADER)) {
      notes.push(`${name} is not a SQLite database`);
      continue;
    }
    // The page gets the main file and nothing beside it.
    const wal = join(outPaths.page(slug), `${name}-wal`);
    if (names.includes(`${name}-wal`) && lstatSync(wal).size > 0) {
      notes.push(`${name}-wal holds changes that are not in ${name} yet, so visitors will not see them — ` +
        'close the database, or run PRAGMA wal_checkpoint(TRUNCATE)');
    }
    if (names.includes(`${name}-journal`)) {
      notes.push(`${name} was left mid-write (${name}-journal is beside it) — close the database`);
    }
  }
  if (databases.length > 0) {
    const loadsKit = names
      .filter((n) => extname(n).toLowerCase() === '.html')
      .some((n) => readPageFile(slug, n, MAX_PAGE_BYTES)?.toString('utf8').includes('/_kit/sqlite.js') === true);
    if (!loadsKit) {
      notes.push(`${databases.join(', ')} cannot be read by the page until it loads /_kit/sqlite.js`);
    }
  }
  return notes;
}

/** Pictures one page may hold. Enough to carry an argument, not a gallery. */
export const MAX_IMAGES_PER_PAGE = 5;

/** How many generated pictures a page already has. */
export function imageCount(slug: string): number {
  try {
    return readdirSync(outPaths.page(slug)).filter((n) => n.toLowerCase().endsWith('.jpg')).length;
  } catch {
    return 0;
  }
}

/**
 * Write a generated picture into a page.
 *
 * Refuses rather than overwrites when the page is full, and refuses a name that
 * is not a slug — this lands as a filename the agent then references from its
 * own HTML, so it is exactly the input a path check exists for.
 */
export function writePageImage(slug: string, name: string, data: Buffer): Published {
  if (!SLUG.test(slug) || !SLUG.test(name)) return { ok: false, error: 'that name is not usable as a file' };
  const dir = outPaths.page(slug);
  const root = resolve(outPaths.pages);
  const target = resolve(dir, `${name}.jpg`);
  if (!target.startsWith(root + sep)) return { ok: false, error: 'that name is not usable as a file' };
  try {
    mkdirSync(dir, { recursive: true });
    writeFileSync(target, data, { mode: 0o644 });
    log('pages.image', { slug, name, bytes: data.length });
    return { ok: true, url: `${name}.jpg` };
  } catch (err) {
    return { ok: false, error: `could not write the picture (${(err as Error).name})` };
  }
}

/**
 * Check what the agent has written and hand back the address.
 *
 * Publishing *is* writing the files; this is the moment the bridge looks at
 * them. Refusals are worded for the agent, because it is the only reader and it
 * can act on them — "there is no index.html" is a thing it can fix.
 */
export function publishPage(slug: string): Published {
  const host = pagesHost();
  if (host === null) return { ok: false, error: 'no page hostname is configured on this deployment' };
  if (!SLUG.test(slug)) {
    return { ok: false, error: 'a page name is 3-48 characters of lowercase letters, digits and dashes' };
  }

  const dir = outPaths.page(slug);
  if (!existsSync(join(dir, 'index.html'))) {
    return { ok: false, error: `write ${slug}/index.html first — a page is served from its index` };
  }
  const stat = measure(slug);
  if (stat === null) return { ok: false, error: 'that page has no files in it' };
  if (stat.files > MAX_FILES_PER_PAGE) {
    return { ok: false, error: `a page may have at most ${String(MAX_FILES_PER_PAGE)} files` };
  }
  if (stat.bytes > MAX_PAGE_BYTES) return { ok: false, error: `that page is larger than ${MAX_PAGE_LABEL}` };

  const existing = listPages();
  if (existing.length > MAX_PAGES && !existing.some((p) => p.slug === slug)) {
    return { ok: false, error: `there are already ${String(MAX_PAGES)} pages — delete one first` };
  }

  log('pages.published', { slug, files: stat.files, bytes: stat.bytes });
  return { ok: true, url: `https://${host}/${slug}/` };
}

/**
 * Unpublishing, and why it is a marker rather than a deletion.
 *
 * A page can now be taken down by whoever was granted it, from a WhatsApp
 * message. That is a good capability and a bad thing to make irreversible: the
 * instruction arrives as natural language, it is acted on by a model, and the
 * person who sent it is not looking at a confirmation dialog. So the verb stops
 * the page being *served* and leaves every byte on disk, and the panel — where
 * there is a human, a list and a confirm — is the only place that removes
 * anything permanently.
 *
 * A file rather than a config entry, deliberately. It lives beside the page it
 * belongs to, so a page restored from a backup carries its own state, and there
 * is no second place to forget to update when a page is deleted for real.
 */
const UNPUBLISHED = '.unpublished';

function pageDir(slug: string): string | null {
  if (!SLUG.test(slug)) return null;
  const root = resolve(outPaths.pages);
  const target = resolve(root, slug);
  return target.startsWith(root + sep) ? target : null;
}

/** Is this page currently withheld from visitors? */
export function isUnpublished(slug: string): boolean {
  const dir = pageDir(slug);
  return dir !== null && existsSync(join(dir, UNPUBLISHED));
}

/** Stop serving a page. Reversible; nothing is removed. */
export function unpublishPage(slug: string): Published {
  const dir = pageDir(slug);
  if (dir === null || !existsSync(dir)) return { ok: false, error: 'there is no page by that name' };
  try {
    writeFileSync(join(dir, UNPUBLISHED), new Date().toISOString());
    log('pages.unpublished', { slug });
    return { ok: true, url: '' };
  } catch (err) {
    log('pages.unpublishFailed', { slug, err: String((err as Error).message) });
    return { ok: false, error: 'the page could not be taken down' };
  }
}

/** Serve it again. */
export function republishPage(slug: string): boolean {
  const dir = pageDir(slug);
  if (dir === null) return false;
  try {
    rmSync(join(dir, UNPUBLISHED), { force: true });
    log('pages.republished', { slug });
    return true;
  } catch {
    return false;
  }
}

/**
 * Per-page passwords, checked here because nowhere else can.
 *
 * A page cannot check its own password. A check written in its own JavaScript
 * would sit in the source the visitor has already downloaded, and the page
 * cannot fetch across origins, so it has nowhere else to send a password to be
 * checked either. The only place a secret can be compared is the side that
 * decides whether to send the bytes at all, which is here — and the same gate
 * guards a write, so the password that unlocks a page is the one that may
 * change it.
 *
 * HTTP Basic, for the same reason: it is the one authentication scheme that
 * needs no page, no form and no fetch, so it survives that CSP untouched. The
 * browser's own dialog is not pretty. It is real, which the alternative was not.
 *
 * The stored value is a salted hash. The operator types a password once and the
 * config keeps something that cannot be read back out of it — the panel renders
 * the whole config, and a page password in plain text there is a password
 * shoulder-surfed.
 */
export interface PagePassword {
  readonly salt: string;
  readonly hash: string;
}

export function hashPagePassword(password: string): PagePassword {
  const salt = randomBytes(16).toString('hex');
  return { salt, hash: scryptSync(password, salt, 32).toString('hex') };
}

function passwordMatches(stored: PagePassword, offered: string): boolean {
  let candidate: Buffer;
  try {
    candidate = scryptSync(offered, stored.salt, 32);
  } catch {
    return false;
  }
  let expected: Buffer;
  try {
    expected = Buffer.from(stored.hash, 'hex');
  } catch {
    return false;
  }
  // Lengths must match before timingSafeEqual, which throws rather than
  // returning false when they do not.
  if (expected.length !== candidate.length) return false;
  return timingSafeEqual(expected, candidate);
}

/**
 * Whether this request may see this page.
 *
 * Returns true when the page is not protected at all, which is the common case
 * and must stay cheap.
 */
export function pageAuthorised(
  stored: PagePassword | undefined,
  authorization: string | undefined,
): boolean {
  if (stored === undefined) return true;
  const raw = (authorization ?? '').trim();
  if (!/^Basic /i.test(raw)) return false;
  let decoded: string;
  try {
    decoded = Buffer.from(raw.slice(6).trim(), 'base64').toString('utf8');
  } catch {
    return false;
  }
  // "user:password" — the user half is ignored. There is one password per page
  // and no notion of who is typing it, and pretending otherwise in the prompt
  // would suggest an account somebody could go and ask for.
  const separator = decoded.indexOf(':');
  if (separator < 0) return false;
  return passwordMatches(stored, decoded.slice(separator + 1));
}

export function deletePage(slug: string): boolean {
  if (!SLUG.test(slug)) return false;
  const root = resolve(outPaths.pages);
  const target = resolve(root, slug);
  if (!target.startsWith(root + sep)) return false;
  try {
    rmSync(target, { recursive: true, force: true });
    log('pages.deleted', { slug });
    return true;
  } catch (err) {
    log('pages.deleteFailed', { slug, err: String((err as Error).message) });
    return false;
  }
}

/**
 * Serve one file from one page.
 *
 * The agent has write access to this directory, so the path is resolved and
 * then re-checked against the root — the same belt-and-braces the outbox file
 * resolver uses, and for the same reason: a name that passed a check is not the
 * same object as a name opened a moment later.
 */
/**
 * Where the pages host sends anyone who arrives at its root.
 *
 * Configurable, and unset is a valid answer. This was one deployment's own
 * marketing site, hardcoded — which is fine for that deployment and wrong for
 * anybody else who runs this, who would be quietly redirecting their visitors
 * to a stranger's homepage.
 *
 * With nothing set, the root answers 404 rather than sending anyone anywhere.
 * The pages host exists to serve `/<slug>/`; its root is not a landing page.
 */
function rootRedirect(): string {
  return (process.env['TULIP_PAGES_ROOT_REDIRECT'] ?? '').trim();
}

/**
 * The design kit, served from a reserved prefix.
 *
 * A page gets Tulip's palette, type and motion by linking two files rather than
 * by the agent reinventing them each time — which is both cheaper and the only
 * way a set of pages looks like one product. Reserved rather than a slug: no
 * page can be called `_kit`, so nothing the agent writes can shadow it.
 */
const KIT_PREFIX = '_kit';
const KIT_FILES: Readonly<Record<string, string>> = {
  'kit.css': 'text/css; charset=utf-8',
  'kit.js': 'text/javascript; charset=utf-8',
  // SQLite, as WebAssembly inlined into a script. Separate from kit.js so a page
  // that has no database never downloads an engine.
  'sqlite.js': 'text/javascript; charset=utf-8',
};
// Beside the compiled bridge, not in `bridge/assets` — the image ships built
// output only, and a path into the source tree resolves to nothing at runtime.
const KIT_DIR = new URL('./web/pagekit/', import.meta.url).pathname;

/**
 * What a page may do: everything a static page does, and nothing that reaches.
 *
 * Same-origin assets, inline script and style so a single file works, and
 * `connect-src 'self'` permits only this isolated pages origin. It lets an
 * interactive page save without navigating while still preventing any request
 * to the panel origin or the wider network.
 *
 * `form-action 'self'`, not `'none'`, and that one word is the whole of how a
 * page writes back. A page with a password may POST a change to its own
 * database (see `applyPageWrite`); the browser carries that as a form
 * submission or an asynchronous request. `'self'` is the pages host, never the
 * panel's — the two are different origins — so this cannot reach the operator's
 * session. Writes remain scoped and password-gated by `servePageWrite`.
 *
 * `'wasm-unsafe-eval'` is here for /_kit/sqlite.js, and it is narrower than it
 * reads: it lets a page compile WebAssembly, and nothing else. It is not
 * `'unsafe-eval'` — no string becomes code — and WebAssembly has no APIs of its
 * own: anything it does, it does through the page's JavaScript, under this same
 * policy. A page could already run any script it liked; now it can run SQLite.
 *
 * One string for every response from the pages host, including scripts: a
 * worker takes its policy from its own script's response, so a script served
 * without this could be started as a worker that answers to nothing.
 */
const PAGE_CSP =
  "default-src 'self'; script-src 'self' 'unsafe-inline' 'wasm-unsafe-eval'; style-src 'self' 'unsafe-inline'; " +
  "img-src 'self' data: blob:; font-src 'self' data:; media-src 'self' data:; " +
  "connect-src 'self'; form-action 'self'; base-uri 'none'; frame-ancestors 'none'";

export function servePage(
  res: ServerResponse,
  url: URL,
  // Optional so every existing caller and test keeps working: a deployment with
  // no protected pages behaves exactly as it did.
  req?: IncomingMessage,
  passwords: Readonly<Record<string, PagePassword>> = {},
): void {
  const parts = url.pathname.split('/').filter((p) => p.length > 0);

  const common = {
    // Same rules as any built page: no outbound connections, nothing embedded.
    'content-security-policy': PAGE_CSP,
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'no-referrer',
    'x-robots-tag': 'noindex, nofollow',
    'cache-control': 'no-cache',
  };

  if (parts[0] === KIT_PREFIX) {
    const file = parts[1] ?? '';
    const type = Object.hasOwn(KIT_FILES, file) ? KIT_FILES[file] : undefined;
    if (type === undefined) {
      res.writeHead(404, { ...common, 'content-type': 'text/plain' }).end('no such file\n');
      return;
    }
    const path = resolve(KIT_DIR, file);
    if (!existsSync(path)) {
      res.writeHead(404, { ...common, 'content-type': 'text/plain' }).end('the kit was not built into this image\n');
      return;
    }
    res.writeHead(200, {
      ...common,
      'content-type': type,
      'content-length': statSync(path).size,
      // Immutable in practice — it changes only when the image is rebuilt, and
      // a page that caches it loads instantly on a second visit.
      'cache-control': 'public, max-age=3600',
    });
    createReadStream(path).pipe(res);
    return;
  }

  // The root is not a directory. Listing every page would make each of them
  // discoverable by anyone who finds the hostname, when the point of a page is
  // that its author hands somebody the link. The operator's own listing lives
  // in the panel, behind the token, where it belongs.
  if (parts.length === 0) {
    // 404 rather than a redirect when nothing is configured. A deployment that
    // has not named a destination should not be sending its visitors to one.
    const destination = rootRedirect();
    if (destination.length === 0) {
      res.writeHead(404, { ...common, 'content-type': 'text/plain; charset=utf-8' }).end('Not found\n');
      return;
    }
    res.writeHead(302, { ...common, location: destination }).end();
    return;
  }

  const slug = parts[0] ?? '';

  // Taken down, and indistinguishable from never having existed. A visitor
  // holding an old link learns nothing about whether it was withdrawn.
  if (SLUG.test(slug) && isUnpublished(slug)) {
    res.writeHead(404, { ...common, 'content-type': 'text/plain; charset=utf-8' }).end('Not found\n');
    return;
  }

  // Before a single byte of the page is read from disk.
  if (SLUG.test(slug) && !pageAuthorised(own(passwords, slug), req?.headers?.authorization)) {
    res.writeHead(401, {
      ...common,
      // The realm is the slug, so a browser holding several pages' passwords
      // keeps them apart instead of offering the wrong one.
      'www-authenticate': `Basic realm="${slug}", charset="UTF-8"`,
      'content-type': 'text/plain; charset=utf-8',
    }).end('This page is password protected.\n');
    return;
  }

  if (!SLUG.test(slug)) {
    res.writeHead(404, { 'content-type': 'text/plain' }).end('no such page\n');
    return;
  }

  const rest = parts.slice(1);
  const name = rest.length === 0 ? 'index.html' : rest[rest.length - 1] ?? 'index.html';
  if (name !== basename(name) || name.startsWith('.')) {
    res.writeHead(400, { 'content-type': 'text/plain' }).end('bad request\n');
    return;
  }
  // A page's database, as the script that carries it. Before the extension
  // allowlist, because `.js` is on it and a file by this name is never read.
  if (name.toLowerCase().endsWith('.js') && DATABASES.has(extname(name.slice(0, -3)).toLowerCase())) {
    serveDatabase(res, slug, name.slice(0, -3), common);
    return;
  }

  const type = TYPES[extname(name).toLowerCase()];
  if (type === undefined) {
    res.writeHead(404, { 'content-type': 'text/plain' }).end('not a servable file\n');
    return;
  }

  const file = openPageFile(slug, name);
  if (file === null) {
    res.writeHead(404, { 'content-type': 'text/plain' }).end('no such page\n');
    return;
  }

  // One byte range, for media seeking and PDF viewers. Anything the parser
  // does not understand is answered whole, as before; a range that lies
  // outside the file is refused with 416, which is what the browser expects.
  const range = parseRange(req?.headers?.range, file.size);
  if (range === 'unsatisfiable') {
    closeSync(file.fd);
    res.writeHead(416, { ...common, 'content-range': `bytes */${String(file.size)}` }).end();
    return;
  }
  const start = range?.start ?? 0;
  const end = range?.end ?? file.size - 1;
  res.writeHead(range ? 206 : 200, {
    ...common,
    'content-type': type,
    'accept-ranges': 'bytes',
    'content-length': file.size === 0 ? 0 : end - start + 1,
    ...(range ? { 'content-range': `bytes ${String(start)}-${String(end)}/${String(file.size)}` } : {}),
  });
  if (file.size === 0) {
    closeSync(file.fd);
    res.end();
    return;
  }
  pipeline(createReadStream('', { fd: file.fd, start, end }), res, (err) => {
    if (err) res.destroy();
  });
}

/**
 * A single `bytes=start-end` range against a file of `size` bytes, or null to
 * serve the whole file, or 'unsatisfiable' when the range starts past the end.
 * Multi-range requests are served whole rather than as multipart; no browser
 * needs them for playback or paging.
 */
export function parseRange(
  header: string | string[] | undefined,
  size: number,
): { start: number; end: number } | null | 'unsatisfiable' {
  if (typeof header !== 'string' || size === 0) return null;
  const m = /^bytes=(\d*)-(\d*)$/.exec(header.trim());
  if (m === null) return null;
  const [, a, b] = m;
  if (a === '' && b === '') return null;
  if (a === '') {
    // Suffix range: the last N bytes.
    const n = Math.min(Number(b), size);
    return n === 0 ? 'unsatisfiable' : { start: size - n, end: size - 1 };
  }
  const start = Number(a);
  if (!Number.isSafeInteger(start) || start >= size) return 'unsatisfiable';
  const end = b === '' ? size - 1 : Math.min(Number(b), size - 1);
  if (end < start) return 'unsatisfiable';
  return { start, end };
}

/**
 * A page's database, delivered as a script.
 *
 * A page cannot fetch anything cross-origin — including a CDN. It can run a
 * same-origin script. So
 * `data.sqlite.js` is answered with one statement handing the bytes of
 * `data.sqlite` to /_kit/sqlite.js, base64-encoded, and the kit opens them.
 * The visitor receives exactly what the file itself would give them; what does
 * not change is that nothing a page does can reach anything.
 *
 * Built from the database every time and never read from a file of that name,
 * so what the kit is handed is always the database and never something the
 * agent wrote to look like one. Streamed, so a database at the page cap is never
 * held whole as a string in the bridge's memory.
 */
function serveDatabase(res: ServerResponse, slug: string, name: string, headers: Record<string, string>): void {
  const file = openPageFile(slug, name);
  if (file === null) {
    res.writeHead(404, { ...headers, 'content-type': 'text/plain' }).end('no such database\n');
    return;
  }
  if (file.size > MAX_PAGE_BYTES) {
    closeSync(file.fd);
    res.writeHead(413, { ...headers, 'content-type': 'text/plain' }).end('that database is larger than a page may hold\n');
    return;
  }

  const head = `(self.__tulipSqlite||(self.__tulipSqlite={}))[${JSON.stringify(name)}]="`;
  const tail = '";\n';
  res.writeHead(200, {
    ...headers,
    'content-type': 'text/javascript; charset=utf-8',
    'content-length': Buffer.byteLength(head) + Math.ceil(file.size / 3) * 4 + Buffer.byteLength(tail),
  });
  res.write(head);
  if (file.size === 0) {
    closeSync(file.fd);
    res.end(tail);
    return;
  }

  // Base64 works in groups of three bytes, and reads arrive in whatever sizes
  // they arrive in: carry the remainder, so no padding lands mid-stream.
  let carry = Buffer.alloc(0);
  const encode = new Transform({
    transform(chunk: Buffer, _encoding, done) {
      const data = carry.length > 0 ? Buffer.concat([carry, chunk]) : chunk;
      const whole = data.length - (data.length % 3);
      carry = Buffer.from(data.subarray(whole));
      done(null, data.subarray(0, whole).toString('base64'));
    },
    flush(done) {
      done(null, carry.toString('base64') + tail);
    },
  });
  pipeline(createReadStream('', { fd: file.fd, start: 0, end: file.size - 1 }), encode, res, (err) => {
    if (err) res.destroy();
  });
}

/**
 * Writing to a page's own database, and the narrow shape of what a page may ask.
 *
 * This is the one thing a page can make happen on the server, and it exists
 * because a roster nobody can change from the page is half a roster. It is
 * deliberately not "run this SQL": the body of a form submitted by a stranger
 * is the most hostile input there is, so nothing in it is ever treated as code.
 * A write names a table, the columns to set, and optionally a row to find — and
 * every one of those names is checked against the database's *actual* schema
 * before it is used, so an identifier that is not already a real column cannot
 * be written at all. Values are bound as parameters and never interpolated.
 *
 * What this does not carry is identity: a page has no account, so any holder of
 * the page's password may change any row. That is the bound the operator chose
 * when they put a password on a page and turned writing on — the password is
 * the whole of who may write, and "only this page" is enforced because the
 * password checked is this page's and the file written is this page's own.
 */
const MAX_WRITE_FIELDS = 40;
const MAX_WRITE_VALUE = 4000;
/** A real SQLite identifier, so a validated name can be quoted without escaping. */
const IDENTIFIER = /^[A-Za-z_][A-Za-z0-9_]*$/;

export interface PageWrite {
  readonly db: string;
  readonly table: string;
  readonly set: ReadonlyArray<readonly [string, string]>;
  readonly where: ReadonlyArray<readonly [string, string]>;
}

/**
 * The absolute path of a page file to write, or null if the way there is not
 * plainly a directory the bridge owns.
 *
 * The same belt-and-braces as reading, in the direction that matters more: a
 * write follows `pages` and `pages/<slug>` as *directories*, refusing either if
 * it is a symlink, so `ln -s /state pages/x` cannot turn a roster update into a
 * write over the WhatsApp session. The leaf itself is allowed to be replaced
 * (the rename below removes a planted link rather than following it).
 */
function writablePagePath(slug: string, name: string): string | null {
  if (!SLUG.test(slug) || name !== basename(name) || name.startsWith('.')) return null;
  if (!DATABASES.has(extname(name).toLowerCase())) return null;
  const root = resolve(outPaths.pages);
  try {
    const rootStat = lstatSync(root);
    if (rootStat.isSymbolicLink() || !rootStat.isDirectory()) return null;
    const dir = join(root, slug);
    const dirStat = lstatSync(dir);
    if (dirStat.isSymbolicLink() || !dirStat.isDirectory()) return null;
    return join(dir, name);
  } catch {
    return null;
  }
}

// Writes to one file are serialised within this process, because two form
// submissions that both copy-edit-rename would otherwise race and one would be
// lost. One bridge process, so an in-memory chain is enough; it is not a
// cross-process lock and does not pretend to be.
const writeChains = new Map<string, Promise<unknown>>();
function serialise<T>(key: string, work: () => Promise<T>): Promise<T> {
  const prior = writeChains.get(key) ?? Promise.resolve();
  const next = prior.then(work, work);
  writeChains.set(key, next.catch(() => {}));
  return next;
}

/**
 * Apply one write to a page's database, atomically for the raw-byte reader.
 *
 * `servePage` reads the file as bytes rather than through SQLite, so SQLite's
 * own atomicity would not protect a reader mid-write. So the change is applied
 * to a private copy and renamed over the original — a reader ever sees one
 * whole file or the other, never a torn one — and the journal mode is forced to
 * the rollback journal so nothing is left in a sidecar the reader would miss.
 */
export function applyPageWrite(slug: string, write: PageWrite): Promise<Published> {
  const path = writablePagePath(slug, write.db);
  if (path === null) return Promise.resolve({ ok: false, error: 'that is not a database in this page' });
  if (write.set.length === 0) return Promise.resolve({ ok: false, error: 'nothing to change' });
  if (write.set.length + write.where.length > MAX_WRITE_FIELDS) {
    return Promise.resolve({ ok: false, error: 'too many fields in one change' });
  }
  if (!IDENTIFIER.test(write.table)) return Promise.resolve({ ok: false, error: 'no such table' });
  for (const [, value] of [...write.set, ...write.where]) {
    if (value.length > MAX_WRITE_VALUE) return Promise.resolve({ ok: false, error: 'a value is too long' });
  }

  return serialise(path, () => Promise.resolve(applyNow(slug, path, write)));
}

function applyNow(slug: string, path: string, write: PageWrite): Published {
  // Work on a private copy read the safe way, so a symlink swapped in for the
  // leaf between the directory checks and here is opened by nobody.
  const bytes = readPageFile(slug, write.db, MAX_PAGE_BYTES);
  if (bytes === null) return { ok: false, error: 'the database could not be read' };
  if (bytes.length > 0 && !bytes.subarray(0, SQLITE_HEADER.length).equals(SQLITE_HEADER)) {
    return { ok: false, error: 'that file is not a SQLite database' };
  }

  const tmp = join(dirname(path), `.${basename(path)}.${randomBytes(6).toString('hex')}.tmp`);
  let db: DatabaseSync | null = null;
  try {
    writeFileSync(tmp, bytes, { mode: 0o644 });
    db = new DatabaseSync(tmp);
    // Rollback journal, not WAL: the served copy is these bytes and nothing
    // beside them, so a change must land in this file or not at all.
    db.exec('PRAGMA journal_mode = DELETE');

    // Every identifier is checked against the schema that is actually there, so
    // only a real table and real columns reach the statement; values are bound.
    const isTable = db.prepare("SELECT 1 FROM sqlite_master WHERE type = 'table' AND name = ?").get(write.table);
    if (isTable === undefined) return { ok: false, error: `no table called ${write.table}` };
    const columns = new Set(
      (db.prepare(`PRAGMA table_info("${write.table}")`).all() as Array<{ name: string }>).map((c) => c.name),
    );
    const known = (pairs: ReadonlyArray<readonly [string, string]>): boolean =>
      pairs.every(([col]) => IDENTIFIER.test(col) && columns.has(col));
    if (!known(write.set) || !known(write.where)) return { ok: false, error: 'a column does not exist' };

    const quote = (id: string): string => `"${id}"`;
    let sql: string;
    let params: string[];
    if (write.where.length === 0) {
      sql = `INSERT INTO "${write.table}" (${write.set.map(([c]) => quote(c)).join(', ')}) ` +
        `VALUES (${write.set.map(() => '?').join(', ')})`;
      params = write.set.map(([, v]) => v);
    } else {
      sql = `UPDATE "${write.table}" SET ${write.set.map(([c]) => `${quote(c)} = ?`).join(', ')} ` +
        `WHERE ${write.where.map(([c]) => `${quote(c)} = ?`).join(' AND ')}`;
      params = [...write.set.map(([, v]) => v), ...write.where.map(([, v]) => v)];
    }

    let changes = 0;
    db.exec('BEGIN IMMEDIATE');
    try {
      const result = db.prepare(sql).run(...params);
      changes = Number(result.changes);
      db.exec('COMMIT');
    } catch (err) {
      db.exec('ROLLBACK');
      return { ok: false, error: `the change was refused (${(err as Error).message})` };
    }
    db.close();
    db = null;

    // Durable, then atomic: fsync the finished copy before the rename, so a
    // crash cannot leave the new name pointing at half-written bytes.
    const fd = openSync(tmp, fsConstants.O_RDONLY);
    try { fsyncSync(fd); } finally { closeSync(fd); }
    renameSync(tmp, path);
    log('pages.wrote', { slug, db: write.db, table: write.table, insert: write.where.length === 0, changes });
    return { ok: true, url: '' };
  } catch (err) {
    return { ok: false, error: `the change could not be saved (${(err as Error).name})` };
  } finally {
    if (db !== null) { try { db.close(); } catch { /* already closing */ } }
    try { rmSync(tmp, { force: true }); } catch { /* best effort */ }
  }
}

/** What a page may be told about a write it asked for. */
export type WriteGate = 'ok' | 'no-password' | 'unauthorised';

/**
 * Whether this request may write this page.
 *
 * Writing turns on with a password and is gated by it: a page with none refuses
 * every write (`no-password`), and a page with one admits only a request that
 * carries it. The same `pageAuthorised` that decides whether to send the bytes
 * decides whether to change them, so the two can never disagree.
 */
export function pageWriteGate(
  stored: PagePassword | undefined,
  authorization: string | undefined,
): WriteGate {
  if (stored === undefined) return 'no-password';
  return pageAuthorised(stored, authorization) ? 'ok' : 'unauthorised';
}

/**
 * Parse a form submission into a write, or null if it is not shaped like one.
 *
 * The wire form is ordinary `application/x-www-form-urlencoded`: `db` and
 * `table`, then `set[col]=value` for each column to write and `where[col]=value`
 * for each column to match. Bracketed names keep the two groups apart without a
 * second request, and a plain HTML form can produce all of it with no script.
 */
export function parsePageWrite(body: string): PageWrite | null {
  const params = new URLSearchParams(body);
  const db = params.get('db') ?? '';
  const table = params.get('table') ?? '';
  if (db === '' || table === '') return null;
  const set: Array<[string, string]> = [];
  const where: Array<[string, string]> = [];
  for (const [key, value] of params) {
    const m = /^(set|where)\[(.+)\]$/.exec(key);
    if (m === null) continue;
    (m[1] === 'set' ? set : where).push([m[2] ?? '', value]);
  }
  return { db, table, set, where };
}

/**
 * Handle a POST to the pages host: a page changing its own database.
 *
 * The body is read by the caller and handed in, because the request plumbing
 * lives in panel.ts with every other body. On success the answer is a 303 back
 * to the page for an ordinary form. A caller that asks for JSON receives a
 * no-navigation response for fetch/XHR clients.
 */
export async function servePageWrite(
  res: ServerResponse,
  url: URL,
  req: IncomingMessage,
  passwords: Readonly<Record<string, PagePassword>>,
  body: string,
): Promise<void> {
  const wantsJson = /(?:^|,)\s*application\/json(?:\s*;|\s*,|\s*$)/i.test(req.headers.accept ?? '');
  const headers = {
    'content-security-policy': PAGE_CSP,
    'x-content-type-options': 'nosniff',
    'referrer-policy': 'no-referrer',
    'x-robots-tag': 'noindex, nofollow',
    'cache-control': 'no-store',
  };
  const slug = url.pathname.split('/').filter((p) => p.length > 0)[0] ?? '';
  if (!SLUG.test(slug) || isUnpublished(slug)) {
    res.writeHead(404, { ...headers, 'content-type': 'text/plain; charset=utf-8' }).end('Not found\n');
    return;
  }

  const gate = pageWriteGate(own(passwords, slug), req.headers?.authorization);
  if (gate === 'no-password') {
    res.writeHead(403, { ...headers, 'content-type': 'text/plain; charset=utf-8' })
      .end('This page does not accept changes.\n');
    return;
  }
  if (gate === 'unauthorised') {
    res.writeHead(401, {
      ...headers,
      'www-authenticate': `Basic realm="${slug}", charset="UTF-8"`,
      'content-type': 'text/plain; charset=utf-8',
    }).end('This page is password protected.\n');
    return;
  }

  const write = parsePageWrite(body);
  if (write === null) {
    res.writeHead(400, { ...headers, 'content-type': 'text/plain; charset=utf-8' }).end('Nothing to change.\n');
    return;
  }

  const result = await applyPageWrite(slug, write);
  if (!result.ok) {
    log('pages.writeRefused', { slug, db: write.db, reason: result.error });
    if (wantsJson) {
      res.writeHead(400, { ...headers, 'content-type': 'application/json; charset=utf-8' })
        .end(JSON.stringify({ ok: false, error: result.error }));
    } else {
      res.writeHead(400, { ...headers, 'content-type': 'text/plain; charset=utf-8' }).end(`${result.error}\n`);
    }
    return;
  }
  if (wantsJson) {
    res.writeHead(200, { ...headers, 'content-type': 'application/json; charset=utf-8' })
      .end(JSON.stringify({ ok: true }));
    return;
  }
  // Back to the page by its directory, never by a path taken from the request:
  // a redirect that echoed user input would be an open redirect on this host.
  res.writeHead(303, { ...headers, location: `/${slug}/` }).end();
}
